name: Build and push Docker image to DockerHub
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
env:
  IMAGE_NAME: amanasterdio/ku-devops-webinar
  IMAGE_TAG: latest
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image (test)
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{env.IMAGE_NAME}}:${{ env.IMAGE_TAG }}
        file: Dockerfile
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_CLI_EXPERIMENTAL: enableds
      id: docker-build
      
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: DOCKERHUB_USERNAME, DOCKERHUB_TOKEN
        script: |
          docker stop $(docker ps -a -q)
          docker login  registry-1.docker.io -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker pull amanasterdio/ku-devops-webinar:latest
          docker run -dit -p 80:80 amanasterdio/ku-devops-webinar:latest
